name = input("What is your name? ")
print(f"Hello, {name}!")
age= input("How old are you? ")
print(f"You are {age} years old.")
favorite_color = input("What is your favorite color? ")
print(f"Your favorite color is {favorite_color}.")